version: "3.9"

services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build: .
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
      MAX_REQUEST_BODY_BYTES: "2000000"
      RATE_LIMIT_REQUESTS_PER_WINDOW: "120"
      RATE_LIMIT_WINDOW_SECONDS: "60"
    ports:
      - "8010:8000"

  worker:
    build: .
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    command: ["uv", "run", "celery", "-A", "app.tasks", "worker", "--loglevel", "info"]
