version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      target: prod
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
      MAX_REQUEST_BODY_BYTES: "2000000"
      RATE_LIMIT_REQUESTS_PER_WINDOW: "120"
      RATE_LIMIT_WINDOW_SECONDS: "60"
    env_file:
      - .env
    ports:
      - "8010:8000"
    volumes:
      - ./.rag_store:/app/.rag_store
      - ./portfolio:/app/portfolio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  worker:
    build:
      context: .
      target: worker
    depends_on:
      redis:
        condition: service_healthy
      api:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    env_file:
      - .env
    volumes:
      - ./.rag_store:/app/.rag_store

volumes:
  redis_data:
