name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          cache: true

      - name: Sync dependencies
        run: uv sync --frozen

      - name: Lint
        run: uv run ruff check .

      - name: Tests
        run: uv run pytest -q
